apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsf.fullname" . }}
  namespace: {{ include "rsf.namespace" . }}
  labels:
    {{- include "rsf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rsf.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
